#setup environment
language: java
sudo: true

jdk:
  - oraclejdk8
  - oraclejdk7

env:
  - NODE_VERSION=7 CC=clang CXX=clang++
  - NODE_VERSION=6 CC=clang CXX=clang++

before_install:
  - nvm install $NODE_VERSION
  - node --version
  - npm  -v

before_script:
  - echo $JAVA_HOME
  - java -version
  - npm install

script:
  - npm run build && npm test

notifications:
  email: false
