#setup environment
language: node_js
node_js:
  - "7"

# build results
notifications:
    email: false

# target OS
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

# build && run tests
before_script: npm install
script: 'npm run build && npm test'
